name: evenloc
description: "Lista de eventos interativa"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter   
  path: ^1.9.0    
  provider: ^6.1.2         
  sqflite: ^2.3.2 

  cupertino_icons: ^1.0.8
  mask_text_input_formatter: ^2.9.0

  google_maps_flutter: ^2.5.0 
  geolocator: ^10.1.0
  geocoding: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icons/logo.png"

flutter_native_splash:
  color: "#00B8D4"
  image: assets/icons/logo.png


flutter:

  uses-material-design: true

